bumping version of the opfcli binary to v0.3.0
operate-first/toolbox pull request #66
Opened 2022-03-24 20:49 UTC by Gregory-Pereira

## Related Issues and Dependencies

Related to: https://github.com/operate-first/opfcli/pull/44

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Bumping version of opfcli to new version `v0.3.0` to include new `onboard` command.

/cc @HumairAK

2022-03-24 20:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Ftoolbox).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/toolbox/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2022-03-24 21:26 UTC, Gregory-Pereira commented
not sure why this failed.
/retest

2022-03-25 00:37 UTC, HumairAK commented
/retest aicoe-ci/build-check

2022-03-25 00:37 UTC, sesheta commented
@HumairAK: The `/retest` command does not accept any targets.
The following commands are available to trigger required jobs:
* `/test pre-commit`

Use `/test all` to run all jobs.


<details>

In response to [this](https://github.com/operate-first/toolbox/pull/66#issuecomment-1078541737):

>/retest aicoe-ci/build-check 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-25 00:37 UTC, HumairAK commented
/retest build-check

2022-03-25 00:37 UTC, sesheta commented
@HumairAK: The `/retest` command does not accept any targets.
The following commands are available to trigger required jobs:
* `/test pre-commit`

Use `/test all` to run all jobs.


<details>

In response to [this](https://github.com/operate-first/toolbox/pull/66#issuecomment-1078541986):

>/retest build-check


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-25 00:37 UTC, HumairAK commented
/test build-check

2022-03-25 00:38 UTC, sesheta commented
@HumairAK: The specified target(s) for `/test` were not found.
The following commands are available to trigger required jobs:
* `/test pre-commit`

Use `/test all` to run all jobs.


<details>

In response to [this](https://github.com/operate-first/toolbox/pull/66#issuecomment-1078542134):

>/test build-check


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-25 00:38 UTC, HumairAK commented
/test  aicoe-ci/build-check

2022-03-25 00:38 UTC, sesheta commented
@HumairAK: The specified target(s) for `/test` were not found.
The following commands are available to trigger required jobs:
* `/test pre-commit`

Use `/test all` to run all jobs.


<details>

In response to [this](https://github.com/operate-first/toolbox/pull/66#issuecomment-1078542352):

>/test  aicoe-ci/build-check


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-25 00:39 UTC, HumairAK commented
stop fighting me sesheta
/test all

2022-03-25 00:41 UTC, HumairAK commented
@harshad16 how can I attempt this build check again?

2022-03-25 00:46 UTC, Gregory-Pereira commented
/test ?

2022-03-25 00:46 UTC, sesheta commented
@Gregory-Pereira: The following commands are available to trigger required jobs:
* `/test pre-commit`

Use `/test all` to run all jobs.


<details>

In response to [this](https://github.com/operate-first/toolbox/pull/66#issuecomment-1078545976):

>/test ?


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-25 00:47 UTC, Gregory-Pereira commented
@HumairAK I don't think this is actually a test, my command above lists all tests and its not showing up. Also the pipeline-run succeeds but the build-check condition fails. Maybe it needs to be added to the `.aicoe-ci.yaml` check value?

2022-03-28 15:38 UTC, Gregory-Pereira commented
/test all

2022-03-28 16:26 UTC, harshad16 commented
/retest

2022-04-14 16:50 UTC, harshad16 commented
/retest

2022-04-14 17:19 UTC, Gregory-Pereira commented
/retest

2022-04-14 20:18 UTC, larsks commented
The commit "[bumping version of the opfcli binary to v0.3.0](https://github.com/operate-first/toolbox/pull/66/commits/c472398c5e7742596e0f1016f41444a983a66b71)" seems to be doing a lot more than just bumping the version of opfcli. Maybe it should be split?

2022-04-14 20:38 UTC, Gregory-Pereira commented
> The commit "[bumping version of the opfcli binary to v0.3.0](https://github.com/operate-first/toolbox/pull/66/commits/c472398c5e7742596e0f1016f41444a983a66b71)" seems to be doing a lot more than just bumping the version of opfcli. Maybe it should be split?

Great point, I am on it. I will remove the version bump with the changes to the underlying images that make it buildable / runable. 
/hold

2022-04-18 12:43 UTC, harshad16 requested changes
let not copy the labels as it make maintenance tougher.
here a suggestion that could work.

2022-04-18 12:43 UTC, harshad16 commented on Dockerfile
> +RUN ls /gen-source/
```suggestion
RUN \
   curl -o /etc/config/labels.yaml https://raw.githubusercontent.com/operate-first/common/main/labels.yaml && \
   cp /etc/config/labels.yaml  /gen-source/labels.yaml
```

we can do this way. move this run command is already present run if this not needed before COPY.

2022-04-21 17:04 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | c46305ea13b35056e89c9cc0525adb28663e5271 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_toolbox/66/pre-commit/1517187525909680128) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=toolbox&pr=66). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/toolbox/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-21 19:52 UTC, Gregory-Pereira commented
Commits have been refactored and tests pass, ready for review @HumairAK @harshad16

2022-04-22 16:24 UTC, harshad16 approved these changes
/lgtm
thanks :100:

2022-04-22 16:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/toolbox/pull/66#pullrequestreview-950322800" title="LGTM">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Ftoolbox).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/toolbox/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2022-04-28 23:52 UTC, HumairAK commented
/lgtm
/approve

2022-04-28 23:52 UTC, HumairAK commented
/unhold

2022-04-28 23:52 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/toolbox/pull/66#pullrequestreview-950322800" title="LGTM">harshad16</a>*, *<a href="https://github.com/operate-first/toolbox/pull/66#issuecomment-1112756412" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Ftoolbox).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/toolbox/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-28 23:55 UTC, merged